disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = ""

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "../assets/ditto.png"

[params.author]
  name = "n3rr"
  image = "../assets/profile.png"