# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/n3rr"

[social.params]
icon = "brand-github"

[[social]]
identifier = "x"
name = "X"
url = "https://x.com/6E3372"

[social.params]
icon = "x"

[[social]]
identifier = "hackthebox"
name = "Hack The Box"
url = "https://app.hackthebox.com/profile/1334425"

[social.params]
icon = "hackthebox"

[[social]]
identifier = "tryhackme"
name = "TryHackMe"
url = "https://tryhackme.com/p/n3r"

[social.params]
icon = "tryhackme" 
