[[main]]
none = "none"

[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Posts"
pageRef = "posts"
weight = 2

[[main]]
name = "About"
pageRef = "about"
weight = 3

[[main]]
name = "Projects"
pageRef = "projects"
weight = 3

[[footer]]
none = "none"
